sudo: false

language: c

addons:
  apt:
    packages:
    - libgmp-dev

cache:
  directories:
    - $HOME/.stack/

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack update
  - stack setup
  - stack build --only-dependencies

script:
  - stack build --test --copy-bins

deploy:
  provider: releases
  api_key:
    secure: iErQYt3dTxO9fQsRButw06hB9ujjhiM199Yc62sB+qV4JxbvrNFMST/BDeulAZGoZQaI7uXb3w6SanQme8ikipx8QceWOU3/+T1SNo3YgwOKuGcwubx805ZyPzEgrYjLbFRUinRfKDjwQJW6OtDZl5FERdNIdK75KiHCE22wWMM=
  file: $HOME/.local/bin/plover
  skip_cleanup: true
  overwrite: true
